version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - '3306:3306'
    volumes:
      #- db:/var/lib/mysql
      - /init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: api
    build:
      context: ./
    image: api
    depends_on:
      - db
    restart: always
    ports:
      - 3001:3001
    links:
      - db
volumes:
  db:
    driver: local